### ISSUE TITLE
Realtime facedetection

### ISSUE THREAD

**Issue by varadig** [marpies/face-detection-ane#1]
I try to made a real time face detection, but some frame, after the session terminated.

Here is my code:

```
package {

import com.greensock.TweenNano;
import com.marpies.ane.facedetection.Face;
import com.marpies.ane.facedetection.FaceDetection;
import com.marpies.ane.facedetection.FaceDetectionAccuracy;
import com.marpies.ane.facedetection.FaceDetectionOptions;

import flash.display.Bitmap;
import flash.display.Sprite;

public class Main extends Sprite {
    private var options:FaceDetectionOptions;

    [Embed(source="obama.png")]
    private var Obama:Class;
    private var obama:Bitmap = new Obama();

    public function Main() {
        FaceDetection.setLogEnabled(true);
        this.options = new FaceDetectionOptions();
        options.accuracy = FaceDetectionAccuracy.HIGH;
        this.addChild(obama);
        this.animate();

    }

    private function animate():void {
        TweenNano.to(this.obama, 1, {
            x: Math.random() * this.stage.stageWidth - this.obama.width,
            y: Math.random() * this.stage.stageHeight - this.obama.height,
            onUpdate: onUpdate,
            onComplete: animate
        })
    }

    private function onUpdate():void {
        FaceDetection.detect(this.obama.bitmapData, onDetectionComplete, options);


    }

    function onDetectionComplete(faces:Vector.<Face>, errorMessage:String):void {
        trace(faces.length);
        if (errorMessage == null) {


        } else {
        }
    }
}
}

```

and the console output

```
Player connected; session starting.
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
[trace] 1
Player session terminated
```

**Comment by dnikolaev** [comment]
Hi @varadig,

Which platform (Android/iOS) and AIR version have you used? Have you seen LogCat/Device logs?

**Comment by marpies** [comment]
Hi @varadig,

The extension does not take the image position into account. Therefore, you do not need to call `FaceDetection.detect` every time the tween updates (you will get the same face data).

In the `onUpdate`, you just need to sum the image position with the face position to get the realtime position in your app.

**Comment by varadig** [comment]
So I can not use the ANE to realtime face detection, just for a still image face detection?

**Comment by marpies** [comment]
Yes, it's meant for static images. Maybe you could run the detection on updated image again in the `onDetectionComplete`, certainly do not do it every frame. The detection is executed in a new thread, so if you execute it too many times it's likely the system will kill your app.

**Comment by danieler1981** [comment]
As i understood is it possibile to call next event inside OnDetectionComplete so it will not start a new thread. My questions are: 1) there is any improvement today? 2) how much fast is the detection on a middle-range device (iPhone6 for example)?

**Comment by marpies** [comment]
@danieler1981 
There has been no change in the functionality, it's still meant for static images. You may get away with running subsequent detections in the complete callback, but I haven't done any extensive testing on this. It's difficult to tell how fast the detection is on a specific device as it can vary depending on the bitmap that's being used. You should run your own tests to see if it suites your needs.
