### ISSUE TITLE
Play Services Update

### ISSUE THREAD

**Issue by AlexUrrutia** [marpies/face-detection-ane#10]
Hello @marpies , could you kindly update this ANE to be compatible with the latest Google Play Services dependencies?
Can't compile face detection ANE with AdMob  ANEs

This is regarding issue #7 

Thanks a lot!

**Comment by marpies** [comment]
Hi @AlexUrrutia,

Try the [v27.1 release](https://github.com/marpies/android-dependency-anes/releases) of the dependency ANEs. The setup below is working for me, i.e. it compiles and detects faces correctly. I'm not sure if the ads are working because I don't have AdMob registered.

```xml
<extensionID>com.marpies.ane.facedetection</extensionID>
<extensionID>com.marpies.ane.androidsupport</extensionID>
<extensionID>com.marpies.ane.googleplayservices.base</extensionID>
<extensionID>com.marpies.ane.googleplayservices.basement</extensionID>
<extensionID>com.marpies.ane.googleplayservices.tasks</extensionID>
<extensionID>com.marpies.ane.googleplayservices.vision</extensionID>

<extensionID>com.myflashlab.air.extensions.admob</extensionID>
<extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.ads.lite</extensionID>
```

**Comment by AlexUrrutia** [comment]
Hello @marpies  I just tested the same setup, and face detection works but no ads are shown, no error trace from AdMob, very strange...

If I use the **flashlabs** basement dependency, it won't compile and returns the error:
[Error.jpg](https://user-images.githubusercontent.com/7042361/37189559-1b9ba730-2323-11e8-81a8-53f7634b2e3d.png)

**Comment by AlexUrrutia** [comment]
@marpies Hello there, after testing different setups I found that the problem is the basement dependency, the following setup works fine:
```

            <extensionID>com.marpies.ane.facedetection</extensionID>
            <extensionID>com.marpies.ane.androidsupport</extensionID>
            <extensionID>com.marpies.ane.googleplayservices.base</extensionID>
            <extensionID>com.marpies.ane.googleplayservices.basement</extensionID>
            <extensionID>com.marpies.ane.googleplayservices.tasks</extensionID>
            <extensionID>com.marpies.ane.googleplayservices.vision</extensionID>

            <extensionID>com.myflashlab.air.extensions.admob</extensionID>
            <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.ads.lite</extensionID>
            <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>

 
```
**but if I just change this basement dependency:**
 `com.marpies.ane.googleplayservices.basement`  **_ADS NOT SHOWN_**
**App will NOT Crash on** `FaceDetection.detect();`

**and replace it with this:** 
` com.myflashlab.air.extensions.dependency.googlePlayServices.basement` **_ADS WORK PERFECT_**

**App will crash on** `FaceDetection.detect();`

any ideas?  thanks!

**Comment by AlexUrrutia** [comment]
@marpies please help!

**Comment by marpies** [comment]
@AlexUrrutia Can you create a sample project for me with Admob ANE and just the code necessary to show some ads? That way I could test it manually myself and see what's wrong.

If you want to share the project privately you can send an email to `support (at) marpies.com`

**Comment by AlexUrrutia** [comment]
@marpies I did, I sent you the repository invitation, thanks a lot, this is very important

**Comment by marpies** [comment]
Try to use [this Vision ANE](https://github.com/marpies/face-detection-ane/files/1979160/vision.ane.zip). I updated it to v12.0.1 which matches the version of MyFlashLabs dependencies. This is the setup I tested, face detection works and ads show up:

```xml
<extensions>
	<extensionID>com.marpies.ane.facedetection</extensionID>
	<extensionID>com.marpies.ane.googleplayservices.vision</extensionID>
	
	<extensionID>com.myflashlab.air.extensions.admob</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.ads.lite</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
</extensions>
```

**Comment by AlexUrrutia** [comment]
@marpies Thank you, it is working now, I appreciate it!
