### ISSUE TITLE
More facial landmarks on Android ?

### ISSUE THREAD

**Issue by Stortof** [marpies/face-detection-ane#2]
Hi there,
First, big thanks for making this ANE open source !
I wonder if you could add all possible facial landmarks when we are using the ane on Android ? This way, we could have a sharper control like on this page : https://developers.google.com/vision/detect-faces-tutorial.
Thanks again.
Best regards.

**Comment by marpies** [comment]
Hi,

Sure, I'll add the rest of the landmarks as soon as I find a moment to work on it.

Regards

**Comment by Stortof** [comment]
GREAT to hear this :)
Best regards.

**Comment by Stortof** [comment]
Really cool to add this so quickly :)
Best.
