### ISSUE TITLE
 Person.Gender - Person.AgeRange

### ISSUE THREAD

**Issue by ciaoamigo** [marpies/face-detection-ane#4]
Hello, and thank you for this extension.
it is possible to find out gender. Eg. If a person is male or female.
Ex.
https://developers.google.com/android/reference/com/google/android/gms/plus/model/people/Person.Gender

**Comment by marpies** [comment]
Hi @ciaoamigo,

Unfortunately, gender recognition is not part of the face detector APIs. The link you provided is part of a different Google Play Services library.
