### ISSUE TITLE
Multidex support for Adobe AIR

### ISSUE THREAD

**Issue by AlexUrrutia** [marpies/face-detection-ane#6]
Regarding bug: https://bugbase.adobe.com/index.cfm?event=bug&id=4190396

This issue has been fixed in AIR SDK 25 Beta. 
Please use latest AIR SDK from - http://labs.adobe.com/downloads/air.html and let us know in case issue still persists.

Thanks,
Adobe AIR Team

**Comment by dnikolaev** [comment]
Hi @AlexUrrutia,

Thank you so much.

Can you check this bug report https://tracker.adobe.com/#/view/AIR-4198266 We're really looking forward to help from Adobe AIR Team.

**Comment by marpies** [comment]
Hi,

Thanks for the notice. Perhaps it's time to remove the note from the readme.

@dnikolaev I voted for the issue. Hopefully they'll be able to fix it before the final version of AIR 25 is out.
