### ISSUE TITLE
Crash when mixing face detection ANE + AdMob ANE

### ISSUE THREAD

**Issue by AlexUrrutia** [marpies/face-detection-ane#7]
Hello we are testing this face detection ANE with AdMob ANE from MilkmanGames, MyFlashLabs, and [lilili87222](https://github.com/lilili87222/admob-for-flash)

The app won't compile, it has several errors regarding Google Play Services, we tried different dependencies and they crash
any Ideas or solutions for this?  is anyone using Face Detection ANE with AdMob ANE?

**Comment by marpies** [comment]
Hi,

Please, post the packaging and crash errors, what dependencies you need and what you have tried. Currently, it's difficult to give you any helpful info.

Thanks

**Comment by AlexUrrutia** [comment]
dx tool failed:
UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/actions/ReserveIntents;

Face Detect ANE + MyFlashLab Google Services ANE : compile error


Face Detect ANE  + Milkman ANE : App Crash on FaceDetection.detect

note: I tried disabling/enabling unnecessary ANEs, this is just my final attempt

Developer Notes: 

> I tried every combination
> “vision” is required for facedetect, but only marpies have the vision ANE, so it’s another issue
> milkman, mfl do not have vision ane
>  so i assume it’s another issue, mixing the anes
> 

![1487887804](https://cloud.githubusercontent.com/assets/7042361/23281380/13542f3c-f9eb-11e6-8727-960ef92d7806.png)

**Comment by AlexUrrutia** [comment]
Face Detect ANE+ Lilili Admob Flash (nogps ANE) = Admob doesn’t work, isInterstitialReady() is always false
Face Detect ANE + lililili Admob Flash (all_in_one) = Compile error
 /private/var/folders/_f/x_jncd3s0p556hwbm4tlg5wr0000gn/T/d404dd41-20cc-49de-aefa-dbce020fe40b/com.google.android.gms.basement-res/values/values.xml:3: error: Attribute "imageAspectRatioAdjust" already defined with incompatible format.
/private/var/folders/_f/x_jncd3s0p556hwbm4tlg5wr0000gn/T/d404dd41-20cc-49de-aefa-dbce020fe40b/res/values/values.xml:34: Original attribute defined here.
/private/var/folders/_f/x_jncd3s0p556hwbm4tlg5wr0000gn/T/d404dd41-20cc-49de-aefa-dbce020fe40b/com.google.android.gms.base-res/values/values.xml:21: error: Attribute "buttonSize" already defined with incompatible format.
/private/var/folders/_f/x_jncd3s0p556hwbm4tlg5wr0000gn/T/d404dd41-20cc-49de-aefa-dbce020fe40b/res/values/values.xml:47: Original attribute defined here.
/private/var/folders/_f/x_jncd3s0p556hwbm4tlg5wr0000gn/T/d404dd41-20cc-49de-aefa-dbce020fe40b/com.google.android.gms.base-res/values/values.xml:21: error: Attribute "colorScheme" already defined with incompatible format.
/private/var/folders/_f/x_jncd3s0p556hwbm4tlg5wr0000gn/T/d404dd41-20cc-49de-aefa-dbce020fe40b/res/values/values.xml:55: Original attribute defined here.

**Comment by AlexUrrutia** [comment]
We also tried the MyFlashLabs Dependencies: https://github.com/myflashlab/common-dependencies-ANE/tree/master/googlePlayServices

But it won't work, app will crash on face detection function, and there is no dependency with the "vision" option from MyFlashLabs

**Comment by Igazine** [comment]
Hi

I'm working with Alex on this project. **We love your work**, it's a great ANE that's easy to use and implement.

We'd like to implement AdMob functionality as well, and so far we tried many others, and either it gives a compiler error, ads won't show up, or FaceDetection.detect crashes the app on Android.

It looks like there's some incompatibility with other Google Services ANEs, we just can't figure out what can be the problem

**Comment by marpies** [comment]
Well, according to what you describe, you either remove a necessary dependency or package two of the same dependencies.

Did you try packaging the all-in-one ANE just with the vision dependency?

```xml
<extensions>
    <extensionID>com.marpies.ane.facedetection</extensionID>
    <extensionID>com.marpies.ane.googleplayservices.vision</extensionID>
    <extensionID>all in one ad mob id</extensionID>
</extensions>
```

I will be able to test it later.

**Comment by AlexUrrutia** [comment]
Yeah I just did, app crashes at `FaceDetection.detect();`

**Comment by marpies** [comment]
Use this vision ANE. It has updated library, that should work with the all-in-one admob ANE. This is the only dependency you need to include when using the all-in-one package.

[com.marpies.ane.googleplayservices.vision.ane.zip](https://github.com/marpies/face-detection-ane/files/799230/com.marpies.ane.googleplayservices.vision.ane.zip)

**Comment by Igazine** [comment]
looks to be working fine!

thanks a lot

**Comment by AlexUrrutia** [comment]
it works!, what was causing the problem?  Thank you!

**Comment by marpies** [comment]
The Admob ANE uses newer version of Google Play Services, it isn't compatible with the version my vision ANE uses. I'll update the dependency ANEs with newer versions in the coming days.

Thanks for reporting.

**Comment by AlexUrrutia** [comment]
Hello Marpies, I am facing the same issue now with the following setup:

```
  <extensionID>com.myflashlab.air.extensions.admob</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
        <extensionID>com.marpies.ane.facedetection</extensionID>
        <extensionID>com.marpies.ane.googleplayservices.vision</extensionID>
        <extensionID>com.marpies.ane.androidsupport</extensionID>
        <extensionID>com.marpies.ane.googleplayservices.basement</extensionID>
        <extensionID>com.marpies.ane.googleplayservices.tasks</extensionID>
     <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.ads.lite</extensionID>
<extensionID>com.marpies.ane.googleplayservices.base</extensionID>
```
![screen shot 2018-03-08 at 10 50 13 pm](https://user-images.githubusercontent.com/7042361/37189559-1b9ba730-2323-11e8-81a8-53f7634b2e3d.png)

If I remove the com.myflashlab.air.extensions.dependency.googlePlayServices.ads.lite . the app compiles but no ads will show, I tried your ads dependency and no ads shown.
If I use flashlabs dependencies, the app will crash at: `FaceDetection.detect();`
Any ideas?  Thank you!
